#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrandr -s 1920x1080 &  # Setting resolution in case of a virtual machine
setxkbmap -layout us -variant intl & # Setting keyboard configuration
xsetroot -cursor_name left_ptr # Setting a proper cursor image
picom -f & # Loading compositor
feh --bg-fill ~/Pictures/wallpapers/cachorro_e_raposa.jpeg # Setting walpaper 
exec bspwm # Start the tiing window manager 
